/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import { PrismaService } from "../../prisma/prisma.service";
import { Prisma, SeoSettings as PrismaSeoSettings } from "@prisma/client";

export class SeoSettingsServiceBase {
  constructor(protected readonly prisma: PrismaService) {}

  async count(
    args: Omit<Prisma.SeoSettingsCountArgs, "select">
  ): Promise<number> {
    return this.prisma.seoSettings.count(args);
  }

  async seoSettingsItems(
    args: Prisma.SeoSettingsFindManyArgs
  ): Promise<PrismaSeoSettings[]> {
    return this.prisma.seoSettings.findMany(args);
  }
  async seoSettings(
    args: Prisma.SeoSettingsFindUniqueArgs
  ): Promise<PrismaSeoSettings | null> {
    return this.prisma.seoSettings.findUnique(args);
  }
  async createSeoSettings(
    args: Prisma.SeoSettingsCreateArgs
  ): Promise<PrismaSeoSettings> {
    return this.prisma.seoSettings.create(args);
  }
  async updateSeoSettings(
    args: Prisma.SeoSettingsUpdateArgs
  ): Promise<PrismaSeoSettings> {
    return this.prisma.seoSettings.update(args);
  }
  async deleteSeoSettings(
    args: Prisma.SeoSettingsDeleteArgs
  ): Promise<PrismaSeoSettings> {
    return this.prisma.seoSettings.delete(args);
  }
}
